"""first schema draft setup

Revision ID: ec9648b47b63
Revises: 
Create Date: 2022-06-28 12:47:15.603214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9648b47b63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constraint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('function', sa.String(), nullable=True),
    sa.Column('mathematical_formulation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constraint_name'), 'constraint', ['name'], unique=True)
    op.create_table('objective',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('function', sa.String(), nullable=True),
    sa.Column('mathematical_formulation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objective_name'), 'objective', ['name'], unique=True)
    op.create_table('problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_name'), 'problem', ['name'], unique=True)
    op.create_table('plot_function',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('type', sa.String(length=12), nullable=True),
    sa.Column('minimum_nr_objectives', sa.Integer(), nullable=True),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('research_link', sa.String(), nullable=True),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variation_name'), 'variation', ['name'], unique=True)
    op.create_table('Variations_have_constraints',
    sa.Column('constraint_id', sa.Integer(), nullable=False),
    sa.Column('variation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['constraint_id'], ['constraint.id'], ),
    sa.ForeignKeyConstraint(['variation_id'], ['variation.id'], ),
    sa.PrimaryKeyConstraint('constraint_id', 'variation_id')
    )
    op.create_table('Variations_have_objectives',
    sa.Column('objective_id', sa.Integer(), nullable=False),
    sa.Column('variation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['objective_id'], ['objective.id'], ),
    sa.ForeignKeyConstraint(['variation_id'], ['variation.id'], ),
    sa.PrimaryKeyConstraint('objective_id', 'variation_id')
    )
    op.create_table('pareto_front',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('algorithm_description', sa.String(), nullable=True),
    sa.Column('research_link', sa.String(), nullable=True),
    sa.Column('variation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['variation_id'], ['variation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pareto_front_name'), 'pareto_front', ['name'], unique=True)
    op.create_table('solution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('representation', sa.PickleType(), nullable=True),
    sa.Column('objective_values', sa.PickleType(), nullable=True),
    sa.Column('pareto_front_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pareto_front_id'], ['pareto_front.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_name'), 'solution', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solution_name'), table_name='solution')
    op.drop_table('solution')
    op.drop_index(op.f('ix_pareto_front_name'), table_name='pareto_front')
    op.drop_table('pareto_front')
    op.drop_table('Variations_have_objectives')
    op.drop_table('Variations_have_constraints')
    op.drop_index(op.f('ix_variation_name'), table_name='variation')
    op.drop_table('variation')
    op.drop_table('plot_function')
    op.drop_index(op.f('ix_problem_name'), table_name='problem')
    op.drop_table('problem')
    op.drop_index(op.f('ix_objective_name'), table_name='objective')
    op.drop_table('objective')
    op.drop_index(op.f('ix_constraint_name'), table_name='constraint')
    op.drop_table('constraint')
    # ### end Alembic commands ###
